package Work4;

public class HWork4 {
    public static void main(String[] args) {
    System.out.println("Задача 1");
    int plumsCount=3;
    System.out.println("Значение переменной plumsCount с типом int равно "+plumsCount);
    byte dogsCount=6;
    System.out.println("Значение переменной dogsCount с типом byte равно "+dogsCount);
    short geeseCount=7;
    System.out.println("Значение переменной geeseCount с типом short равно "+geeseCount);
    long fishCount= 89000766600L;
    System.out.println("Значение переменной fishCount с типом long равно "+fishCount);
    float pi=3.14f;
    System.out.println("Значение переменной pi с типом float равно "+pi);
    double e =2.8;
    System.out.println("Значение переменной e с типом doubl равно "+e);
        System.out.println("Задача 2");
        float variable1=27.12f;
        long variable2=987_678_965_549L;
        double variable3=2.786;
        boolean variable4=false;
        short variable5=569;
        int variable6=-159;
        char variable7=27897;
        byte variable8=67;
        System.out.println("Задача 3");
        int pupilsInFirstClass=23;
        int pupilsInSecondClass=27;
        int pupilsInThirdClass=30;
        int papersCount=480;
        int papersPerPuls=papersCount/(pupilsInFirstClass+pupilsInSecondClass+pupilsInThirdClass);
        System.out.println( "На каждого ученика рассчитано "  +papersPerPuls+"  листов бумаги");
        System.out.println("Задача 4");
        int bottles=16;
        int minutes =2;
        int produktivityPerMinute=bottles/minutes;
        int twentyMinutes=20;
        System.out.println("За"+twentyMinutes +" минут машина произвела бутылок " +produktivityPerMinute*twentyMinutes + " штук ");
        int minutesInDay=24*60;
        System.out.println("За"+minutesInDay +"минут машина произвела бутылок " +produktivityPerMinute*minutesInDay + " штук ");
        int minutesInThreeDay=3*minutesInDay;
        System.out.println("За"+minutesInThreeDay +" минут машина произвела бутылок " +produktivityPerMinute *minutesInThreeDay + " штук ");
        int minutesInMonth=30*minutesInDay;
        System.out.println("За "+minutesInMonth +" минут машина произвела бутылок " +produktivityPerMinute*minutesInMonth + " штук ");
        System.out.println("Задача 5");
        int totalNumberOfCans=120;
        byte whitePaint=2;
        byte brownPaint=4;
        int numberOfCansPerClass=totalNumberOfCans/(whitePaint+brownPaint);
        int totalWhitePaint=whitePaint*numberOfCansPerClass;
        int totalBrownPaint= brownPaint* numberOfCansPerClass;
        System.out.println("В школе, где "+numberOfCansPerClass+" классов, нужно "+totalWhitePaint + " банок белой краски и"+totalBrownPaint + " банок коричневой краски");
        System.out.println("Задача 6");
        byte bananes=5;
        int bananaWeight=bananes*80;
        double milk=200;
        double milkWeght=milk/105F;
        int iceCream=2*100;
        int eggs=4;
        int eggsWeght=eggs*70;
        double totalWeght=bananaWeight+milkWeght+iceCream+eggsWeght;
        double totalWeghtKg=totalWeght/1000;
        System.out.printf("Общий вес продуктов составляет:  %.2f\n",  totalWeghtKg );
        System.out.println("Задача 7");
        int loseWeightKg=7;
        int loseWeightGr=loseWeightKg*1000;
        int loseWeightDayFirst=250;
        int  loseWeightDaySecond =500;
        double firstWay=loseWeightGr/loseWeightDayFirst;
        double secondDay=loseWeightGr/loseWeightDaySecond;
        System.out.println(""+firstWay+" дней уйдёт на похудение, если спортсмен будет терять каждый день по 250 грамм");
;       System.out.println(""+secondDay+" дней уйдёт на похудение, если спортсмен будет терять каждый день по 500 грамм");
        System.out.println("Задача 8");
         int mashaCurrentSalary=67760;
         int denisCurrentSalary=83690;
         int kristinaCurrentSalary=76230;
         double mashaIncreasedSalary=mashaCurrentSalary*1.1;
         double denisIncreasedSalary=denisCurrentSalary*1.1F;
         double kristinaIncreasedSalary=kristinaCurrentSalary*1.1;
         double mahsaAnnualSalary=(mashaIncreasedSalary-mashaCurrentSalary)*12;
         double denisAnnualSalary=(denisIncreasedSalary-denisCurrentSalary)*12;
         double kristinaAnnualSalary=(kristinaIncreasedSalary-kristinaCurrentSalary)*12;
         System.out.println( "Маша теперь получает " +mashaIncreasedSalary+" рублей. Годовой доход вырос на "+mahsaAnnualSalary+" рублей");
         System.out.printf( "Денис теперь получает " +denisIncreasedSalary+" рублей. Годовой доход вырос на "+denisAnnualSalary+" рублей");
         System.out.println( "Кристина теперь получает " +kristinaIncreasedSalary+" рублей. Годовой доход вырос на "+kristinaAnnualSalary+" рублей");
        System.out.println("Задачи повышенной сложности");
        System.out.println("Задача 9");
      byte a = 12;
      byte b = 27;
      byte c = 44;
      byte d = 15;
      byte e1 = 9;
      int result = a * (b + (c - d * e1));
        System.out.println(result);
        int result1 = - (a * (b + (c - d * e1)));
        System.out.println(result1);
        System.out.println("Задача 10");
        int a1 =5;
        int b1=7;
        System.out.printf("a=%d b=%d\n",a1,b1);
        a1=a1+b1;
        b1=a1-b1;
        a1=a1-b1;
        System.out.printf("a=%d b=%d\n",a1,b1);
        System.out.println("Задача 11");
        int a2 = 396;
        int b2 = a2 % 100/10;
        System.out.println(b2);

    }
}